package models;
// Generated 13.1.2017 16:33:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int idCategory;
     private String description;
     private int coefficient;
     private Set evaluationItems = new HashSet(0);

    public Category() {
    }

	
    public Category(int idCategory, String description, int coefficient) {
        this.idCategory = idCategory;
        this.description = description;
        this.coefficient = coefficient;
    }
    public Category(int idCategory, String description, int coefficient, Set evaluationItems) {
       this.idCategory = idCategory;
       this.description = description;
       this.coefficient = coefficient;
       this.evaluationItems = evaluationItems;
    }
   
    public int getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(int idCategory) {
        this.idCategory = idCategory;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getCoefficient() {
        return this.coefficient;
    }
    
    public void setCoefficient(int coefficient) {
        this.coefficient = coefficient;
    }
    public Set getEvaluationItems() {
        return this.evaluationItems;
    }
    
    public void setEvaluationItems(Set evaluationItems) {
        this.evaluationItems = evaluationItems;
    }




}


